// Code generated by "stringer -type LogType -trimprefix LogType"; DO NOT EDIT.

package config

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LogTypeText-0]
	_ = x[LogTypeJSON-1]
}

const _LogType_name = "TextJson"

var _LogType_index = [...]uint8{0, 4, 8}

func (i LogType) String() string {
	if i < 0 || i >= LogType(len(_LogType_index)-1) {
		return "LogType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LogType_name[_LogType_index[i]:_LogType_index[i+1]]
}
