---
name: Go Test and Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  GO_VERSION: '1.23.1'

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }} 

    - name: Lint Go Code
      uses: golangci/golangci-lint-action@v6.1.0

    - name: Test 
      run: go test -short -v ./...

    - uses: hoverkraft-tech/compose-action@v2.0.2
      with:
        down-flags: --volumes
        services: |
          postgres
          postgres-migration

    - name: Run Integration Tests
      run: go test -v -run '^TestIntegration_' ./...
    
    - name: Build server 
      run: go build -o server ./cmd/server

    - name: Build burl
      run: go build -o client ./cmd/burl