---
name: "Pull Request Labeler"

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - ".github/labeler.yaml"
      - ".github/workflows/labeler.yaml"
  pull_request:
    paths:
      - ".github/labeler.yaml"
      - ".github/workflows/labeler.yaml"

permissions:
  contents: read
  pull-requests: write

jobs:
  labeler:
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    steps:
      - name: Label PR based on policy in labeler.yaml
        uses: actions/labeler@v5
        if: startsWith(github.event_name, 'pull_request') && github.event.action != 'closed'
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/labeler.yaml