#!/bin/bash

set -euo pipefail

linter() {
  echo "Running Go linter..."
  if task lint; then
    echo "Linter passed!"
  else
    echo "Linter failed. Please fix the issues before committing."
    exit 1
  fi
}

linter
